### PR TITLE
Add danRer10

### PR DESCRIPTION
**Pull request by natefoo**

### CODE REVIEW

**Comment by natefoo** [comment]
@galaxybot deploy this

**Comment by lldelisle** [comment]
When you try to get the bundle of STAR you get a 'No space left on device'...

**Comment by natefoo** [comment]
Yes, this is probably trying to do too much in one batch, but the specific issue is most likely with the size of the filesystem used by OverlayFS on the Jenkins worker. Right now we have this intermediate step of exporting from idc-build and importing on the Jenkins worker, then we rsync the imported changes over to CVMFS. But it would be simpler to just import directly on the CVMFS server. I will create an issue for this.

**Comment by natefoo** [comment]
Note to self for when I get back to this: Fix and merge #31, [implement this](https://github.com/galaxyproject/idc/issues/22#issuecomment-1636949295), rebase, and drop the bowtie 1 builder from all genomes.

**Comment by natefoo** [comment]
@galaxybot deploy this

**Comment by natefoo** [comment]
Weird failure since there's no reason the ssh socket would be removed and was used successfully in the previous command... anyway, publishing did work!

**Pull request merged**
