### PR TITLE
Attempt to make build and import independently idempotent

### PR DESCRIPTION
**Pull request by natefoo**
This is the second half of the stuff mentioned in #30.

### CODE REVIEW

**Comment by natefoo** [comment]
Really confused at the error here - this bundle URL worked for all the others, except that before it was fetching from the idc-build VM instead of Main directly. The download link from Main is a zip containing only the json (with an html extension: `Bowtie2_index_data_manager_json.html`) but that's it, no data. Does the idc user need to be an admin? @jmchilton any idea what's going on here? All the other histories that worked when importing directly from the idc-build VM appear to just be only the "html" json file in a zip when downloaded from usegalaxy.org.

Error:
```pytb
Traceback (most recent call last):
  File "/usr/local/bin/galaxy-import-data-bundle", line 8, in <module>
    sys.exit(run_import_data_bundle())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/galaxy_maintenance_scripts/import_data_bundle.py", line 39, in run_import_data_bundle
    table_manager.import_bundle(
  File "/usr/local/lib/python3.9/site-packages/galaxy/tool_util/data/__init__.py", line 1165, in import_bundle
    with open(index_json) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpyiju8k42/gx_file_streamtklmu_fe/_gx_data_bundle_index.json'
```

Bundle URL: https://usegalaxy.org/api/datasets/f9cad7b01a472135e65a12013f404721/display?to_ext=data_manager_json
History URL: https://usegalaxy.org/histories/view?id=77f695ab944b984b

**Comment by natefoo** [comment]
I'm wondering if #16508 is related.

**Comment by natefoo** [comment]
@galaxybot deploy this

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Comment by mvdbeek** [comment]
Hmm, some progress, it seems like the data is now in the bundle, but we're still missing the manifest ?

**Comment by mvdbeek** [comment]
@galaxybot deploy this

**Comment by natefoo** [comment]
One step closer! Thank you @mvdbeek.

**Pull request merged**
